spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: pc-verse

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/pc_verse}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

keycloak:
  issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8090/realms/pcverse}
  jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8090/realms/pcverse/protocol/openid-connect/certs}
  resource-client-id: ${KEYCLOAK_RESOURCE_CLIENT_ID:pc-verse-api}

server:
  port: ${SERVER_PORT:8085}
