spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: pc-verse

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/pc_verse}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: ${AZURE_KEY_VAULT_ENDPOINT}

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-url: http://localhost:8090/realms/pc-verse-client

jwt:
  access-token:
    private-key: ${jwt-access-private-key-base64:${JWT_ACCESS_PRIVATE_KEY_BASE64}}
    public-key: ${jwt-access-public-key-base64:${JWT_ACCESS_PUBLIC_KEY_BASE64}}
  refresh-token:
    secret-key: ${jwt-refresh-secret-key:${JWT_REFRESH_SECRET_KEY}}

keycloak:
  resource-client-id: ${KEYCLOAK_RESOURCE_CLIENT_ID:pc-verse-api}

server:
  port: ${SERVER_PORT:8085}
