package com.pcverse.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@AllArgsConstructor
@Getter
public enum ErrorCode {

    INTERNAL_ERROR(500, "Unexpected error occurred while processing request in backend service", HttpStatus.INTERNAL_SERVER_ERROR),
    VALIDATION_ERROR(400, "Invalid request data", HttpStatus.BAD_REQUEST),
    UNSUPPORTED_MEDIA_TYPE(415, "Unsupported request Content-Type", HttpStatus.UNSUPPORTED_MEDIA_TYPE),
    USER_ALREADY_EXISTS(409, "User already exists", HttpStatus.CONFLICT),
    OPTIMISTIC_LOCKING_CONFLICT(409, "Optimistic locking conflict", HttpStatus.CONFLICT),
    USER_NOT_FOUND(404,"User not found", HttpStatus.NOT_FOUND),
    USER_SEARCH_FIELD_REQUIRED(400, "User search field is required", HttpStatus.BAD_REQUEST),
    USER_SEARCH_VALUE_REQUIRED(400, "User search value is required", HttpStatus.BAD_REQUEST),
    TOKEN_INVALID(401, "Invalid token", HttpStatus.UNAUTHORIZED),
    TOKEN_EXPIRED(401, "Token is expired", HttpStatus.UNAUTHORIZED),
        TOKEN_REVOKED(401, "Token has been revoked", HttpStatus.UNAUTHORIZED),
    TOKEN_GENERATION_FAILED(500, "Token generation failed", HttpStatus.INTERNAL_SERVER_ERROR),
    KEYCLOAK_ADMIN_API_ERROR(502, "Unable to complete the user operation in Keycloak", HttpStatus.BAD_GATEWAY),
    KEYCLOAK_USER_NOT_FOUND(404, "User does not exist in Keycloak", HttpStatus.NOT_FOUND),
    KEYCLOAK_PERMISSION_DENIED(502, "The Keycloak service account does not have permission to perform this operation", HttpStatus.BAD_GATEWAY),
    PASSWORD_POLICY_VIOLATION(
            400,
            "Password does not meet the configured password policy",
            HttpStatus.BAD_REQUEST
    ),
    NO_FIELDS_TO_UPDATE(400, "No fields to update", HttpStatus.BAD_REQUEST),
    KEYCLOAK_USER_NOT_LINKED(409, "User is not linked to a Keycloak account", HttpStatus.CONFLICT),
    USER_STATUS_NOT_SUPPORTED(400, "This user status cannot be synchronized with Keycloak", HttpStatus.BAD_REQUEST),
    USER_ACCOUNT_INACTIVE(403, "User account is not active", HttpStatus.FORBIDDEN),
    UNAUTHORIZED(401, "Vui lòng đăng nhập để truy cập", HttpStatus.UNAUTHORIZED),
    FORBIDDEN(403, "Không có quyền truy cập", HttpStatus.FORBIDDEN),
    MISSING_LOGOUT_INFO(400, "Authorization header or refresh token is missing", HttpStatus.BAD_REQUEST),
    USER_ROLE_NOT_ASSIGNED(404,"Role is not assigned to this user", HttpStatus.NOT_FOUND),
    USER_SESSION_NOT_FOUND(404, "User session not found", HttpStatus.NOT_FOUND),
    ROLE_NOT_FOUND(404, "Role not found", HttpStatus.NOT_FOUND),
    ADDRESS_NOT_FOUND(404, "Address not found", HttpStatus.NOT_FOUND),
    CATEGORY_ALREADY_EXISTS(409, "Category already exists", HttpStatus.CONFLICT),
    CATEGORY_CONCURRENT_MODIFICATION(409, "Category was modified by another request. Please retry", HttpStatus.CONFLICT),
    CATEGORY_NAME_REQUIRED(400, "Category name must not be null or blank", HttpStatus.BAD_REQUEST),
    CATEGORY_NAME_INVALID(400, "Category name must produce a non-empty slug", HttpStatus.BAD_REQUEST),
    CATEGORY_NOT_FOUND(404, "Category not found", HttpStatus.NOT_FOUND),
    CATEGORY_INACTIVE(400, "Category is inactive", HttpStatus.BAD_REQUEST),
    CATEGORY_VERSION_REQUIRED(400, "Category version must not be null", HttpStatus.BAD_REQUEST),
    CATEGORY_IN_USE(409, "Category is in use", HttpStatus.CONFLICT),
    CATEGORY_HAS_ACTIVE_PRODUCTS(409, "Category has active products", HttpStatus.CONFLICT),
    CATEGORY_DATA_INTEGRITY_VIOLATION(409, "Category data conflicts with existing data", HttpStatus.CONFLICT),
    INVALID_CATEGORY_DATA_TYPE(400, "Invalid category data type", HttpStatus.BAD_REQUEST),
    CATEGORY_SEARCH_FIELD_REQUIRED(400, "Category search field is required", HttpStatus.BAD_REQUEST),
    CATEGORY_SEARCH_VALUE_REQUIRED(400, "Category search value is required", HttpStatus.BAD_REQUEST),
    PRODUCT_NOT_FOUND(404, "Product not found", HttpStatus.NOT_FOUND),
    PRODUCT_ACCESS_DENIED(403, "You do not have permission to access this product", HttpStatus.FORBIDDEN),
    PRODUCT_SEARCH_FIELD_REQUIRED(400, "Product search field is required", HttpStatus.BAD_REQUEST),
    PRODUCT_SEARCH_VALUE_REQUIRED(400, "Product search value is required", HttpStatus.BAD_REQUEST),
    PRODUCT_STOCK_AVAILABILITY_REQUIRED(400, "Product stock availability is required", HttpStatus.BAD_REQUEST),
    PRODUCT_PRICE_RANGE_REQUIRED(400, "Product price range is required", HttpStatus.BAD_REQUEST),
    PRODUCT_PRICE_INVALID(400, "Product price is invalid", HttpStatus.BAD_REQUEST),
    PRODUCT_PRICE_RANGE_INVALID(400, "Product price range is invalid", HttpStatus.BAD_REQUEST),
    PRODUCT_CONCURRENT_MODIFICATION(409, "Product was modified by another request. Please retry", HttpStatus.CONFLICT),
    PRODUCT_VERSION_REQUIRED(400, "Product version must not be null", HttpStatus.BAD_REQUEST),
    PRODUCT_SKU_ALREADY_EXISTS(409, "Product SKU already exists", HttpStatus.CONFLICT),
    PRODUCT_SLUG_ALREADY_EXISTS(409, "Product slug already exists", HttpStatus.CONFLICT),
    PRODUCT_NAME_INVALID(400, "Product name must produce a non-empty slug", HttpStatus.BAD_REQUEST),
    PRODUCT_ACTIVE_CANNOT_DELETE(409, "Active product cannot be deleted", HttpStatus.CONFLICT),
    PRODUCT_IMAGE_REQUIRED(409, "At least one image is required to activate product", HttpStatus.CONFLICT),
    PRODUCT_REQUIRED_ATTRIBUTES_MISSING(409, "Required product attributes are missing", HttpStatus.CONFLICT),
    PRODUCT_ATTRIBUTE_DUPLICATE(409, "A product attribute definition was provided more than once", HttpStatus.CONFLICT),
    PRODUCT_ATTRIBUTE_NOT_ALLOWED(400, "Attribute is not assigned to the product category", HttpStatus.BAD_REQUEST),
    PRODUCT_CATEGORY_CHANGE_NOT_ALLOWED(409, "Cannot change category while product has attribute values", HttpStatus.CONFLICT),
    BRAND_NOT_FOUND(404, "Brand not found", HttpStatus.NOT_FOUND),
    BRAND_INACTIVE(400, "Brand is inactive", HttpStatus.BAD_REQUEST),
    PRODUCT_DATA_INTEGRITY_VIOLATION(409, "Product data conflicts with existing data", HttpStatus.CONFLICT),
    BRAND_NAME_INVALID(400, "Brand name must produce a non-empty slug", HttpStatus.BAD_REQUEST),
    BRAND_NAME_REQUIRED(400, "Brand name is required", HttpStatus.BAD_REQUEST),
    BRAND_DATA_INTEGRITY_VIOLATION(
            409,
            "Brand data conflicts with existing data",
            HttpStatus.CONFLICT
    ),
    BRAND_ALREADY_EXISTS(409, "Brand already exists", HttpStatus.CONFLICT),
    BRAND_CONCURRENT_MODIFICATION(409, "Brand was modified by another request. Please retry", HttpStatus.CONFLICT),
    BRAND_HAS_ACTIVE_PRODUCTS(409, "Brand has active products", HttpStatus.CONFLICT),
    BRAND_VERSION_REQUIRED(400, "Brand version must not be null", HttpStatus.BAD_REQUEST),
    BRAND_IN_USE(409, "Brand is in use", HttpStatus.CONFLICT),
    PRODUCT_USE_CASE_NOT_FOUND(404, "Product use case not found", HttpStatus.NOT_FOUND),
    CPU_NOT_FOUND(404, "CPU not found", HttpStatus.NOT_FOUND),
    INVALID_ATTRIBUTE_DATA_TYPE(400, "Invalid attribute data type for this operation", HttpStatus.BAD_REQUEST),
    ATTRIBUTE_DEFINITION_INTEGRITY_VIOLATION(409, "Attribute definition integrity violation", HttpStatus.CONFLICT),
    ATTRIBUTE_DEFINITION_NOT_FOUND(404, "Attribute definition not found", HttpStatus.NOT_FOUND),
    ATTRIBUTE_NOT_FOUND(404, "Attribute not found", HttpStatus.NOT_FOUND),
    ATTRIBUTE_DEFINITION_INACTIVE(400, "Attribute definition is inactive", HttpStatus.BAD_REQUEST),
    ATTRIBUTE_OPTION_ALREADY_EXISTS(409, "Attribute option already exists", HttpStatus.CONFLICT),
    ATTRIBUTE_DEFINITION_CONCURRENT_MODIFICATION(409, "Attribute definition was modified by another request. Please retry", HttpStatus.CONFLICT),
    ATTRIBUTE_DEFINITION_ALREADY_EXISTS(409, "Attribute definition already exists", HttpStatus.CONFLICT),
    ATTRIBUTE_DEFINITION_DATA_TYPE_REQUIRED(409, "Attribute definition data type is required", HttpStatus.BAD_REQUEST),
    ATTRIBUTE_DEFINITION_IN_USE(409, "Attribute definition in use", HttpStatus.CONFLICT),
    ATTRIBUTE_DEFINITION_NAME_REQUIRED(400, "Attribute definition name is required", HttpStatus.BAD_REQUEST),
    CATEGORY_ATTRIBUTE_ALREADY_EXISTS(409, "Category attribute already exists", HttpStatus.CONFLICT),
    ATTRIBUTE_OPTION_NOT_FOUND(404, "Attribute option not found", HttpStatus.NOT_FOUND),
    ATTRIBUTE_OPTION_INACTIVE(400, "Attribute option is inactive", HttpStatus.BAD_REQUEST),
    ATTRIBUTE_OPTION_IN_USE(409, "Attribute option in use", HttpStatus.CONFLICT),
    ATTRIBUTE_OPTION_CONCURRENT_UPDATE(409, "Attribute option was modified by another request. Please retry", HttpStatus.CONFLICT),
    CATEGORY_ATTRIBUTE_NOT_FOUND(404, "Category attribute not found", HttpStatus.NOT_FOUND),
    CATEGORY_ATTRIBUTE_IN_USE(409, "Category attribute in use", HttpStatus.CONFLICT),
    CATEGORY_ATTRIBUTE_CONCURRENT_UPDATE(409, "Category attribute was modified by another request. Please retry", HttpStatus.CONFLICT),
    CATEGORY_ATTRIBUTE_VERSION_REQUIRED(400, "Version must not be null", HttpStatus.BAD_REQUEST),;

    private final int code;
    private final String message;
    private final HttpStatus httpStatus;


}
